//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/JS Vehicle Physics Controller/Logitech Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @LogitechControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @LogitechControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Logitech Controls"",
    ""maps"": [
        {
            ""name"": ""Car Input "",
            ""id"": ""d5fb92d9-e412-4b23-a17f-5a744bd1b589"",
            ""actions"": [
                {
                    ""name"": ""Steering"",
                    ""type"": ""PassThrough"",
                    ""id"": ""dc012cc1-8bdb-4af3-bda4-d33c3cbd8cf8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Brake"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8d2c6b50-824a-4eef-88a5-0bc119169c41"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Accelerate"",
                    ""type"": ""Value"",
                    ""id"": ""8fe3b02b-9bea-4723-b456-508e06fa5c9a"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ShiftUp"",
                    ""type"": ""Button"",
                    ""id"": ""ede8a645-9d77-4156-9c41-88fd3458b7b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShiftDown"",
                    ""type"": ""Button"",
                    ""id"": ""27152a54-62d4-4f0d-ac5a-a4a8c780878d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2817132b-7b30-4647-828c-b00e8ee03903"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""258d24ee-5661-46cd-9bc0-7efb934d67c2"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dbb96688-0925-440b-8053-be2b238d58ae"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accelerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84325034-cc2d-41bb-abc6-571dbeafb614"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShiftUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16aae38d-50d4-404c-a514-ba2bb7e7f6fc"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShiftDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Car Input 
        m_CarInput = asset.FindActionMap("Car Input ", throwIfNotFound: true);
        m_CarInput_Steering = m_CarInput.FindAction("Steering", throwIfNotFound: true);
        m_CarInput_Brake = m_CarInput.FindAction("Brake", throwIfNotFound: true);
        m_CarInput_Accelerate = m_CarInput.FindAction("Accelerate", throwIfNotFound: true);
        m_CarInput_ShiftUp = m_CarInput.FindAction("ShiftUp", throwIfNotFound: true);
        m_CarInput_ShiftDown = m_CarInput.FindAction("ShiftDown", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Car Input 
    private readonly InputActionMap m_CarInput;
    private List<ICarInputActions> m_CarInputActionsCallbackInterfaces = new List<ICarInputActions>();
    private readonly InputAction m_CarInput_Steering;
    private readonly InputAction m_CarInput_Brake;
    private readonly InputAction m_CarInput_Accelerate;
    private readonly InputAction m_CarInput_ShiftUp;
    private readonly InputAction m_CarInput_ShiftDown;
    public struct CarInputActions
    {
        private @LogitechControls m_Wrapper;
        public CarInputActions(@LogitechControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Steering => m_Wrapper.m_CarInput_Steering;
        public InputAction @Brake => m_Wrapper.m_CarInput_Brake;
        public InputAction @Accelerate => m_Wrapper.m_CarInput_Accelerate;
        public InputAction @ShiftUp => m_Wrapper.m_CarInput_ShiftUp;
        public InputAction @ShiftDown => m_Wrapper.m_CarInput_ShiftDown;
        public InputActionMap Get() { return m_Wrapper.m_CarInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CarInputActions set) { return set.Get(); }
        public void AddCallbacks(ICarInputActions instance)
        {
            if (instance == null || m_Wrapper.m_CarInputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CarInputActionsCallbackInterfaces.Add(instance);
            @Steering.started += instance.OnSteering;
            @Steering.performed += instance.OnSteering;
            @Steering.canceled += instance.OnSteering;
            @Brake.started += instance.OnBrake;
            @Brake.performed += instance.OnBrake;
            @Brake.canceled += instance.OnBrake;
            @Accelerate.started += instance.OnAccelerate;
            @Accelerate.performed += instance.OnAccelerate;
            @Accelerate.canceled += instance.OnAccelerate;
            @ShiftUp.started += instance.OnShiftUp;
            @ShiftUp.performed += instance.OnShiftUp;
            @ShiftUp.canceled += instance.OnShiftUp;
            @ShiftDown.started += instance.OnShiftDown;
            @ShiftDown.performed += instance.OnShiftDown;
            @ShiftDown.canceled += instance.OnShiftDown;
        }

        private void UnregisterCallbacks(ICarInputActions instance)
        {
            @Steering.started -= instance.OnSteering;
            @Steering.performed -= instance.OnSteering;
            @Steering.canceled -= instance.OnSteering;
            @Brake.started -= instance.OnBrake;
            @Brake.performed -= instance.OnBrake;
            @Brake.canceled -= instance.OnBrake;
            @Accelerate.started -= instance.OnAccelerate;
            @Accelerate.performed -= instance.OnAccelerate;
            @Accelerate.canceled -= instance.OnAccelerate;
            @ShiftUp.started -= instance.OnShiftUp;
            @ShiftUp.performed -= instance.OnShiftUp;
            @ShiftUp.canceled -= instance.OnShiftUp;
            @ShiftDown.started -= instance.OnShiftDown;
            @ShiftDown.performed -= instance.OnShiftDown;
            @ShiftDown.canceled -= instance.OnShiftDown;
        }

        public void RemoveCallbacks(ICarInputActions instance)
        {
            if (m_Wrapper.m_CarInputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICarInputActions instance)
        {
            foreach (var item in m_Wrapper.m_CarInputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CarInputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CarInputActions @CarInput => new CarInputActions(this);
    public interface ICarInputActions
    {
        void OnSteering(InputAction.CallbackContext context);
        void OnBrake(InputAction.CallbackContext context);
        void OnAccelerate(InputAction.CallbackContext context);
        void OnShiftUp(InputAction.CallbackContext context);
        void OnShiftDown(InputAction.CallbackContext context);
    }
}
